#!/usr/bin/env bash
# Nginx listening to port 80
sed -i -E 's/listen [0-9]+.+;/listen 80 default_server;/g' /etc/nginx/sites-enabled/default
sed -i -E 's/listen \[::\]:.+;/\n/g' /etc/nginx/sites-enabled/default
sudo /etc/init.d/nginx start
sudo /etc/init.d/nginx restart
