#!/usr/bin/env bash
# This script configures an Ubuntu server with the below requirements.
cp /etc/hosts ~/hosts.cpy
sed -i s/127.0.0.1/127.0.0.2/g ~/hosts.cpy
echo "8.8.8.8 facebook.com" >> ~/hosts.cpy
cp -f ~/hosts.cpy /etc/hosts
