#!/usr/bin/env bash
#Just give me a page
brew install wget apache2 -y
echo "Hello Holberton" > /var/www/html/index.html 
echo "ServerName localhost" >> /etc/apache2/apache2.conf
/etc/init.d/apache2 start
